name: yolov3-tf2-cpu

dependencies:
  - python==3.7
  - pip
  - matplotlib
  - opencv
  - scikit-learn
  - pillow
  - beautifulsoup4
  - lxml
  - pip:
    - tensorflow>=2.1
    - lxml
    - tqdm
    - -e .
    - numpy
